#!/bin/bash

folder_path=$1

defaultFolder="/home/eric/work/002-processing/"
if [ -z "$folder_path" ]; then
  read -p "Use '${defaultFolder}'? (y/n)" CHOICE
  CHOICE=${CHOICE:-y}
  if [ ${CHOICE} == "y" ]; then
    folder_path=${defaultFolder}
  else
    echo "Must set a full path folder!!!"
    echo ""
    exit 1
  fi 
fi  


echo "Target parent folder is: ${folder_path}"

cd "${folder_path}"

# look up sub folders
for d in */; do
  if [ $d != "*/" ]; then
    # rar-tuzac each sub folder
    rar-tuzac "${d}"
  fi  
done
