#!/bin/bash

folder_path=$1

echo "Target parent folder is: ${folder_path}"

cd "${folder_path}"

# look up sub folders
for d in */; do
  if [ $d != "*/" ]; then
    # rar-tuzac each sub folder
    image_resize_wm.sh "${d}"
  fi  
done
