#!/bin/bash

folder_path=$1

if [ -z "$folder_path" ]; then
  read -p "Use '/mnt/wd8t/jw-hd-no-watermark/02-processing/'? (y/n)" CHOICE
  CHOICE=${CHOICE:-y}
  if [ ${CHOICE} == "y" ]; then
    folder_path="/mnt/wd8t/jw-hd-no-watermark/02-processing/"
  else
    echo "Must set a full path folder!!!"
    echo ""
    exit 1
  fi 
fi

echo "Target parent folder is: ${folder_path}"

cd "${folder_path}"

# look up sub folders
for d in */; do
  if [ $d != "*/" ]; then
    # rar-tuzac each sub folder
    image_resize_wm.sh "${d}"
  fi  
done
